"""Reusable, deterministic fixture runner; expectations are never generated by a reader."""

import json
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from bancaemdia.coleta.readers.base import (
    CanonicalBet,
    ReaderEnvelope,
    canonical_bytes,
    decode_raw,
    digest,
)
from bancaemdia.coleta.readers.errors import ReaderError
from bancaemdia.coleta.readers.registry import ReaderRegistry
from bancaemdia.coleta.readers.safety import check_safe


class FixtureContractError(ValueError):
    pass


def bundle_digest(manifest: dict) -> str:
    return digest(
        canonical_bytes({key: value for key, value in manifest.items() if key != "review"})
    )


# Owner instruction of 2026-10-06: publish this exact synthetic candidate for PR review.
# This is publication authorization, never administrator approval or real-host evidence.
FIXTURE_SHA256 = "4df5308bfc391564e6e2cb0e6ace49e29f7194a640f5c74ce53aec55353de601"


def owner_authorized_candidate(manifest: dict) -> bool:
    return (
        bundle_digest(manifest) == FIXTURE_SHA256
        and manifest.get("review")
        == {
            "status": "publication_authorized",
            "reviewer": None,
            "reference": None,
            "bundle_sha256": FIXTURE_SHA256,
        }
        and (
            manifest.get("evidence_kind"),
            manifest.get("reader_id"),
            manifest.get("brand"),
            manifest.get("hostname"),
            manifest.get("last_real_capture_at"),
        )
        == ("synthetic", "synthetic_reference", "example", "reader.example.invalid", None)
    )


def reviewed_manifest(directory: Path) -> dict:
    if directory.is_symlink():
        raise FixtureContractError("unsafe_fixture_directory")
    manifest = json.loads((directory / "manifest.json").read_text(encoding="utf-8"))
    review = manifest["review"]
    # Review links permit only the repository's public comment anchor, never a capture URL.
    if review.get("reference") is not None and not re.fullmatch(
        r"https://github\.com/pradyumna-001/bancaemdia-api/(?:issues|pull)/\d+#issuecomment-\d+",
        review["reference"],
    ):
        raise FixtureContractError("invalid_human_review_reference")
    # Hex SHA-256 metadata can coincidentally contain phone/CPF digit sequences.
    # Validate its format separately; scan every payload and all other metadata normally.
    hashes = [review.get("bundle_sha256")]
    hashes.extend(value for fixture in manifest["fixtures"] for value in fixture["files"].values())
    if any(
        not isinstance(value, str) or not re.fullmatch(r"[0-9a-f]{64}", value) for value in hashes
    ):
        raise FixtureContractError("invalid_sha256_metadata")
    screening = {
        **manifest,
        "review": {**review, "reference": None, "bundle_sha256": None},
        "fixtures": [
            {**fixture, "files": dict.fromkeys(fixture["files"])}
            for fixture in manifest["fixtures"]
        ],
    }
    check_safe(screening)
    if not owner_authorized_candidate(manifest) and (
        review.get("status") != "approved"
        or not review.get("reviewer")
        or not review.get("reference")
        or review.get("bundle_sha256") != bundle_digest(manifest)
    ):
        raise FixtureContractError("human_review_missing_or_changed")
    for field in ("fixture_set_version", "reader_version"):
        if not re.fullmatch(r"(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)", manifest[field]):
            raise FixtureContractError("stable_version_required")
    if manifest["evidence_kind"] not in {"synthetic", "sanitized_real", "legacy"}:
        raise FixtureContractError("unknown_evidence_kind")
    if manifest["evidence_kind"] == "sanitized_real":
        stamp = datetime.fromisoformat(manifest["last_real_capture_at"].replace("Z", "+00:00"))
        if stamp.utcoffset() is None:
            raise FixtureContractError("real_capture_date_requires_timezone")
    elif manifest["last_real_capture_at"] is not None:
        raise FixtureContractError("synthetic_or_legacy_is_not_current_real_evidence")
    expected_paths = {"manifest.json"}
    names = set()
    for fixture in manifest["fixtures"]:
        if not re.fullmatch(r"[a-z0-9][a-z0-9_-]{0,63}", fixture["name"]):
            raise FixtureContractError("unsafe_fixture_name")
        if fixture["name"] in names:
            raise FixtureContractError("duplicate_fixture")
        names.add(fixture["name"])
        filenames = {
            fixture["name"] + "." + suffix
            for suffix in ("raw.json", "envelope.json", "golden.json")
        }
        if set(fixture["files"]) != filenames:
            raise FixtureContractError("raw_envelope_and_golden_required")
        for filename, expected_hash in fixture["files"].items():
            path = directory / filename
            if (
                path.name != filename
                or path.is_symlink()
                or not path.is_file()
                or len(path.read_bytes()) > 256 * 1024
            ):
                raise FixtureContractError("unsafe_fixture_path_or_size")
            if digest(path.read_bytes()) != expected_hash:
                raise FixtureContractError("fixture_changed_without_review")
            expected_paths.add(filename)
    if not names or {p.name for p in directory.iterdir()} != expected_paths:
        raise FixtureContractError("empty_or_unlisted_fixture")
    return manifest


def fixture_contents(directory: Path, name: str) -> tuple[dict, dict]:
    raw = (directory / (name + ".raw.json")).read_bytes()
    decode_raw(raw.decode("utf-8"))
    envelope = json.loads((directory / (name + ".envelope.json")).read_text(encoding="utf-8"))
    parsed = ReaderEnvelope.model_validate(envelope)
    check_safe(parsed.model_dump(mode="json", exclude={"payload_text"}))
    if parsed.payload_text.encode("utf-8") != raw:
        raise FixtureContractError("envelope_must_preserve_raw_bytes")
    golden = json.loads((directory / (name + ".golden.json")).read_text(encoding="utf-8"))
    check_safe(golden)
    return envelope, golden


def run_fixture_set(directory: Path, registry: ReaderRegistry) -> dict:
    manifest = reviewed_manifest(directory)
    failures = []
    states = set()
    for fixture in manifest["fixtures"]:
        envelope, golden = fixture_contents(directory, fixture["name"])
        if any(
            envelope[field] != manifest[field]
            for field in ("brand", "hostname", "raw_schema_version")
        ):
            raise FixtureContractError("manifest_provenance_mismatch")
        try:
            if manifest.get("money_contract") == 2:
                from bancaemdia.coleta.readers.one_win import OneWinReader

                native = OneWinReader().parse_native(ReaderEnvelope.model_validate(envelope))
                if (native.reader_id, native.reader_version) != (
                    manifest["reader_id"],
                    manifest["reader_version"],
                ):
                    raise FixtureContractError("manifest_reader_version_mismatch")
                actual = {"bets": [native.model_dump(mode="json")]}
            else:
                result = registry.read(envelope)
                if (result.reader_id, result.reader_version) != (
                    manifest["reader_id"],
                    manifest["reader_version"],
                ):
                    raise FixtureContractError("manifest_reader_version_mismatch")
                actual = {"bets": [b.model_dump(mode="json") for b in result.bets]}
        except ReaderError as error:
            actual = {"error_code": error.code.value, "reason": error.reason}
        if actual != golden:
            failures.append({"fixture": fixture["name"], "drift_reason": "golden_mismatch"})
        else:
            actual_states = {b["state"] for b in actual.get("bets", [])}
            if actual.get("error_code") == "unsupported_market":
                actual_states.add("UNSUPPORTED")
            if fixture["covered_state"] not in actual_states:
                raise FixtureContractError("manifest_state_mismatch")
            states.add(fixture["covered_state"])
    return {
        "brand": manifest["brand"],
        "hostname": manifest["hostname"],
        "reader_id": manifest["reader_id"],
        "reader_version": manifest["reader_version"],
        "raw_schema_version": manifest["raw_schema_version"],
        "fixture_set_version": manifest["fixture_set_version"],
        "money_contract": manifest.get("money_contract", 1),
        "fixture_count": len(manifest["fixtures"]),
        "covered_states": sorted(states),
        "last_real_capture_at": manifest["last_real_capture_at"],
        "evidence_kind": manifest["evidence_kind"],
        "review_status": manifest["review"]["status"],
        "passed": not failures,
        "drift_reason": None if not failures else "golden_mismatch",
        "failures": failures,
        "production_support_proven": False
        if manifest["evidence_kind"] != "sanitized_real"
        else None,
    }


@dataclass
class GoldenReplay:
    """Contract-level replay oracle; financial persistence is proved by the #115 regression suite."""

    bets: dict[str, CanonicalBet]

    def apply(self, parsed) -> list[str]:
        results = []
        for incoming in parsed.bets:
            old = self.bets.get(incoming.identity_hash)
            if old is None:
                self.bets[incoming.identity_hash] = incoming
                results.append("created")
            elif old.canonical_hash == incoming.canonical_hash:
                results.append("noop")
            elif incoming.source_updated_at > old.source_updated_at:
                self.bets[incoming.identity_hash] = incoming
                results.append("updated")
            else:
                results.append("stale_or_conflicting")
        return results
