CASAS: tuple[tuple[str, str], ...] = (
    ("Betano", "betano.bet.br"),
    ("bet365", "bet365.bet.br"),
    ("Superbet", "superbet.bet.br"),
    ("KTO", "kto.bet.br"),
    ("BetMGM", "betmgm.bet.br"),
    ("Betfair", "betfair.bet.br"),
    ("Esportiva Bet", "esportiva.bet.br"),
    ("Betnacional", "betnacional.bet.br"),
    ("Bolsa de Aposta", "bolsadeaposta.bet.br"),
    ("KingPanda", "kingpanda.bet.br"),
    ("Sportingbet", "sportingbet.bet.br"),
    ("Lottu", "lottu.bet.br"),
    ("BetFast", "betfast.bet.br"),
    ("Esportes da Sorte", "esportesdasorte.bet.br"),
    ("BetPix365", "betpix365.bet.br"),
    ("VaideBet", "vaidebet.bet.br"),
    ("Novibet", "novibet.bet.br"),
    ("Casa de Apostas", "casadeapostas.bet.br"),
    ("Betsson", "betsson.bet.br"),
    ("Faz1 Bet", "faz1.bet.br"),
    ("Jogo de Ouro", "jogodeouro.bet.br"),
    ("BetEsporte", "betesporte.bet.br"),
    ("Stake", "stake.bet.br"),
    ("Betboo", "betboo.bet.br"),
    ("Aposta Ganha", "apostaganha.bet.br"),
    ("Pinnacle", "pinnacle.bet.br"),
    ("EstrelaBet", "estrelabet.bet.br"),
    ("BetBoom", "betboom.bet.br"),
    ("7K Bet", "7k.bet.br"),
    ("7Games", "7games.bet.br"),
    ("Blaze", "blaze.bet.br"),
    ("VBet", "vbet.bet.br"),
    ("JonBet", "jonbet.bet.br"),
    ("Meridianbet", "meridianbet.bet.br"),
    ("BetSul", "betsul.bet.br"),
    ("BandBet", "bandbet.bet.br"),
    ("MC Games", "mcgames.bet.br"),
    ("Pagol", "pagol.bet.br"),
    ("Vupi", "vupi.bet.br"),
    ("Pitaco", "pitaco.bet.br"),
    ("Ginga", "ginga.bet.br"),
    ("ApostaMax", "apostamax.bet.br"),
    ("JogaJunto", "jogajunto.bet.br"),
    ("BetGo", "betgo.bet.br"),
    ("Afun", "afun.bet.br"),
    ("Bet da Sorte", "betdasorte.bet.br"),
    ("BetVIP", "betvip.bet.br"),
    ("Bateu", "bateu.bet.br"),
    ("Tivo", "tivo.bet.br"),
    ("Pix.bet", "pix.bet.br"),
    ("Bingo Plus", "bingoplus.bet.br"),
    ("Betgorillas", "betgorillas.bet.br"),
    ("4Play", "4play.bet.br"),
    ("Betão", "betao.bet.br"),
)

ESPORTES: tuple[tuple[str, str], ...] = (
    ("Futebol", "⚽"),
    ("Basquete", "🏀"),
    ("Tênis", "🎾"),
    ("MMA", "🥊"),
    ("F1", "🏎"),
    ("Futebol Americano", "🏈"),
    ("Beisebol", "⚾"),
    ("Vôlei", "🏐"),
    ("Handebol", "🤾"),
    ("E-sports", "🎮"),
)

COMPETICOES: tuple[tuple[str, str, str], ...] = (
    ("Brasileirão Série A", "Futebol", "Brasil"),
    ("Brasileirão Série B", "Futebol", "Brasil"),
    ("Copa do Brasil", "Futebol", "Brasil"),
    ("Campeonato Paulista", "Futebol", "Brasil"),
    ("Campeonato Carioca", "Futebol", "Brasil"),
    ("Campeonato Mineiro", "Futebol", "Brasil"),
    ("Campeonato Gaúcho", "Futebol", "Brasil"),
    ("Copa Libertadores", "Futebol", "América do Sul"),
    ("Copa Sul-Americana", "Futebol", "América do Sul"),
    ("Copa América", "Futebol", "América do Sul"),
    ("Premier League", "Futebol", "Inglaterra"),
    ("La Liga", "Futebol", "Espanha"),
    ("Serie A", "Futebol", "Itália"),
    ("Bundesliga", "Futebol", "Alemanha"),
    ("Ligue 1", "Futebol", "França"),
    ("UEFA Champions League", "Futebol", "Europa"),
    ("UEFA Europa League", "Futebol", "Europa"),
    ("Eurocopa", "Futebol", "Europa"),
    ("Copa do Mundo", "Futebol", "Mundial"),
    ("NBA", "Basquete", "Estados Unidos"),
    ("NBB", "Basquete", "Brasil"),
    ("Australian Open", "Tênis", "Austrália"),
    ("Roland Garros", "Tênis", "França"),
    ("Wimbledon", "Tênis", "Inglaterra"),
    ("US Open", "Tênis", "Estados Unidos"),
    ("UFC", "MMA", "Estados Unidos"),
    ("Fórmula 1", "F1", "Mundial"),
    ("NFL", "Futebol Americano", "Estados Unidos"),
    ("MLB", "Beisebol", "Estados Unidos"),
    ("Superliga de Vôlei", "Vôlei", "Brasil"),
    ("Liga Nacional de Handebol", "Handebol", "Brasil"),
    ("CBLOL", "E-sports", "Brasil"),
    ("League of Legends World Championship", "E-sports", "Mundial"),
)

MERCADOS: tuple[tuple[str, str], ...] = (
    ("Escanteios — Handicap", "ESCANTEIOS"),
    ("Escanteios — 1º Tempo", "ESCANTEIOS"),
    ("Escanteios — 2º Tempo", "ESCANTEIOS"),
    ("Escanteios — por Time", "ESCANTEIOS"),
    ("Total de Escanteios", "ESCANTEIOS"),
    ("Cartões — Handicap", "CARTOES"),
    ("Cartões — por Time", "CARTOES"),
    ("Cartão Vermelho", "CARTOES"),
    ("Jogador — Cartão", "JOGADOR"),
    ("Total de Cartões", "CARTOES"),
    ("Jogador — Faltas Sofridas", "JOGADOR"),
    ("Jogador — Faltas Cometidas", "JOGADOR"),
    ("Jogador — Chutes de Fora da Área", "JOGADOR"),
    ("Jogador — Chutes no Gol", "JOGADOR"),
    ("Jogador — Total de Chutes", "JOGADOR"),
    ("Jogador — Desarmes", "JOGADOR"),
    ("Jogador — Assistências", "JOGADOR"),
    ("Jogador — Defesas", "JOGADOR"),
    ("Jogador — Passes", "JOGADOR"),
    ("Jogador — Dribles", "JOGADOR"),
    ("Jogador — Impedimentos", "JOGADOR"),
    ("Jogador — Marcar a Qualquer Momento", "JOGADOR"),
    ("Jogador — Marcar Primeiro", "JOGADOR"),
    ("Gols — 1º Tempo", "GOLS"),
    ("Gols — 2º Tempo", "GOLS"),
    ("Ambas as Equipes Marcam", "AMBAS_MARCAM"),
    ("Equipe Marca nos Dois Tempos", "GOLS"),
    ("Próximo Gol", "GOLS"),
    ("Placar Exato", "GOLS"),
    ("Total de Gols", "GOLS"),
    ("Resultado — 1º Tempo", "RESULTADO"),
    ("Chance Dupla", "RESULTADO"),
    ("Empate Anula", "RESULTADO"),
    ("Handicap Asiático", "RESULTADO"),
    ("Handicap Europeu", "RESULTADO"),
    ("Vencer Algum Tempo", "RESULTADO"),
    ("Classificação / Avanço", "RESULTADO"),
    ("Resultado da Partida", "RESULTADO"),
    ("Luta — Método de Vitória", "RESULTADO"),
    ("Luta — Total de Rounds", "RESULTADO"),
    ("Luta — Vai até o Fim", "RESULTADO"),
    ("Luta — Vencedor", "RESULTADO"),
    ("Basquete — Pontos do Jogador", "JOGADOR"),
    ("Basquete — Rebotes", "JOGADOR"),
    ("Basquete — Triplos", "JOGADOR"),
    ("Basquete — Duplo-Duplo", "JOGADOR"),
    ("Tênis — Total de Games", "OUTRO"),
    ("Tênis — Total de Sets", "OUTRO"),
    ("Tênis — Tie-break", "OUTRO"),
    ("F1 — Pódio / Top 3", "RESULTADO"),
    ("F1 — Classificação", "RESULTADO"),
    ("F1 — Volta Mais Rápida", "RESULTADO"),
    ("F1 — Comparativo entre Pilotos", "RESULTADO"),
    ("Substituição Garantida", "OUTRO"),
    ("Laterais / Arremessos", "OUTRO"),
    ("Tiros de Meta", "OUTRO"),
    ("Jogador — Melhor em Campo", "JOGADOR"),
    ("Beisebol — Corridas", "OUTRO"),
    ("Gols em Ambos os Tempos", "GOLS"),
    ("Escanteios — por Equipe", "ESCANTEIOS"),
    ("Faltas — Total da Partida", "OUTRO"),
    ("Intervalo / Final", "RESULTADO"),
    ("Margem de Vitória", "RESULTADO"),
    ("Time a Marcar Primeiro", "GOLS"),
    ("Time a Marcar por Último", "GOLS"),
    ("Gols Ímpar / Par", "GOLS"),
    ("Não Sofrer Gols", "GOLS"),
    ("Tempo do Primeiro Gol", "GOLS"),
    ("Hat-trick", "JOGADOR"),
    ("Pênalti na Partida", "OUTRO"),
    ("Gol Contra", "GOLS"),
    ("Resultado e Ambas Marcam", "RESULTADO"),
    ("Corrida de Escanteios", "ESCANTEIOS"),
    ("Vôlei — Total de Pontos", "OUTRO"),
    ("Vôlei / Tênis — Vencedor do Set", "OUTRO"),
    ("E-sports — Total de Mortes", "OUTRO"),
    ("E-sports — Total de Mapas", "OUTRO"),
    ("E-sports — Abates", "OUTRO"),
)

TIMES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Flamengo", ("CR Flamengo", "Flamengo RJ", "Fla")),
    ("Palmeiras", ("SE Palmeiras", "Palmeiras SP")),
    ("Corinthians", ("SC Corinthians", "Corinthians SP", "Timão")),
    ("São Paulo", ("Sao Paulo", "São Paulo FC", "SPFC")),
    ("Santos", ("Santos FC", "Santos SP")),
    ("Vasco da Gama", ("Vasco", "CR Vasco da Gama")),
    ("Botafogo", ("Botafogo-RJ", "Botafogo RJ", "Botafogo FR")),
    ("Fluminense", ("Fluminense FC", "Flu")),
    ("Grêmio", ("Gremio", "Grêmio RS", "Gremio RS", "Grêmio FBPA")),
    ("Internacional", ("Inter", "SC Internacional", "Internacional RS")),
    ("Atlético-MG", ("Atletico Mineiro", "Atlético Mineiro", "Atletico-MG", "Galo", "CAM")),
    ("Cruzeiro", ("Cruzeiro EC", "Cruzeiro MG")),
    ("Bahia", ("EC Bahia", "Bahia BA")),
    ("Vitória", ("Vitoria", "EC Vitória", "Vitória BA")),
    ("Fortaleza", ("Fortaleza EC", "Fortaleza CE")),
    ("Ceará", ("Ceara", "Ceará SC")),
    ("Athletico-PR", ("Athletico Paranaense", "Atletico-PR", "Atlético-PR", "CAP")),
    ("Coritiba", ("Coritiba FC", "Coxa")),
    ("Sport", ("Sport Recife", "Sport Club do Recife")),
    ("Red Bull Bragantino", ("Bragantino", "RB Bragantino")),
    ("Juventude", ("EC Juventude", "Juventude RS")),
    ("Mirassol", ("Mirassol FC", "Mirassol SP")),
    ("Chapecoense", ("Chape", "Chapecoense SC")),
    ("Goiás", ("Goias", "Goiás EC")),
    ("América-MG", ("America Mineiro", "América Mineiro", "America-MG")),
    ("Cuiabá", ("Cuiaba", "Cuiabá EC")),
    ("Atlético-GO", ("Atletico Goianiense", "Atlético Goianiense", "Atletico-GO")),
    ("Criciúma", ("Criciuma", "Criciúma EC")),
    ("Vila Nova", ("Vila Nova FC", "Vila Nova GO")),
    ("Avaí", ("Avai", "Avaí FC")),
    ("Ponte Preta", ("AA Ponte Preta", "Ponte Preta SP")),
)
