"""Generate the checked-in OpenAPI contract and its Markdown reference.

The application lifespan is intentionally not started: FastAPI builds the OpenAPI
document from registered routes without connecting to PostgreSQL or Redis.
"""

from __future__ import annotations

import argparse
import importlib
import json
import os
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

DEFAULT_SOURCE_ROOT = Path("src")
DEFAULT_SCHEMA_OUTPUT = Path("tests/contract/schemas/openapi.json")
DEFAULT_DOCS_OUTPUT = Path("docs/API.md")

_SAFE_ENV_DEFAULTS = {
    "APP_ENV": "testing",
    "COLETA_TOKEN_SECRET": "openapi-generation-only",
    "DATABASE_URL": "postgresql+asyncpg://user:password@localhost:5432/bancaemdia",
    "DATABASE_URL_REPLICA": "postgresql+asyncpg://user:password@localhost:5432/bancaemdia",
    "JWT_ALGORITHM": "RS256",
    "JWT_AUDIENCE": "bancaemdia-api",
    "JWT_ISSUER": "bancaemdia-api",
    "JWT_SECRET_KEY": "openapi-generation-only",
    "LOG_LEVEL": "WARNING",
    "OTEL_EXPORTER_OTLP_ENDPOINT": "",
    "RATE_LIMIT_STORAGE": "memory://",
    "REDIS_URL": "redis://localhost:6379/0",
    "STATEMENT_TIMEOUT_PRIMARY": "5000",
    "STATEMENT_TIMEOUT_REPLICA": "30000",
}

_HTTP_METHODS = ("get", "post", "put", "patch", "delete", "options", "head", "trace")


def _parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the deterministic OpenAPI snapshot and API reference.",
    )
    parser.add_argument(
        "--source-root",
        type=Path,
        default=DEFAULT_SOURCE_ROOT,
        help="Directory containing the bancaemdia package (default: src).",
    )
    parser.add_argument(
        "--schema-output",
        type=Path,
        default=DEFAULT_SCHEMA_OUTPUT,
        help=(
            "Destination for the deterministic OpenAPI JSON "
            "(default: tests/contract/schemas/openapi.json)."
        ),
    )
    parser.add_argument(
        "--docs-output",
        type=Path,
        default=DEFAULT_DOCS_OUTPUT,
        help="Destination for the generated Markdown reference (default: docs/API.md).",
    )
    parser.add_argument(
        "--schema-only",
        action="store_true",
        help="Generate or check only the OpenAPI JSON snapshot.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated content differs from checked-in files; do not write files.",
    )
    return parser.parse_args(argv)


def _configure_generation_environment() -> None:
    for name, value in _SAFE_ENV_DEFAULTS.items():
        os.environ.setdefault(name, value)


def _load_openapi(source_root: Path) -> dict[str, Any]:
    source_root = source_root.resolve()
    if not source_root.is_dir():
        raise FileNotFoundError(f"source root does not exist or is not a directory: {source_root}")

    _configure_generation_environment()
    sys.path.insert(0, os.fspath(source_root))
    try:
        module = importlib.import_module("bancaemdia.main")
        schema = module.app.openapi()
    finally:
        sys.path.pop(0)

    if not isinstance(schema, dict):
        raise TypeError("FastAPI app.openapi() did not return an object")
    return schema


def _serialize_schema(schema: Mapping[str, Any]) -> str:
    return json.dumps(schema, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def _markdown_cell(value: object) -> str:
    text = str(value or "—").strip().replace("\r", " ").replace("\n", " ")
    return text.replace("|", "\\|")


def _render_api_docs(schema: Mapping[str, Any], schema_output: Path, docs_output: Path) -> str:
    info = schema.get("info")
    info = info if isinstance(info, Mapping) else {}
    paths = schema.get("paths")
    paths = paths if isinstance(paths, Mapping) else {}

    title = _markdown_cell(info.get("title", "Bancaemdia API"))
    version = _markdown_cell(info.get("version", "unknown"))
    openapi_version = _markdown_cell(schema.get("openapi", "unknown"))
    schema_link = Path(os.path.relpath(schema_output, start=docs_output.parent)).as_posix()

    lines = [
        "<!-- Generated by scripts/generate_openapi.py. Do not edit manually. -->",
        "",
        f"# {title}",
        "",
        f"API version: `{version}` · OpenAPI: `{openapi_version}`",
        "",
        "The checked-in [OpenAPI contract]"
        f"({schema_link}) is the source of truth for this reference.",
        "With the API running locally, use [Swagger UI](http://localhost:8000/docs) or "
        "[ReDoc](http://localhost:8000/redoc) for an interactive view.",
        "",
        "Regenerate both artifacts with:",
        "",
        "```bash",
        "python scripts/generate_openapi.py",
        "```",
        "",
        "## Endpoints",
        "",
        "| Method | Path | Summary | Responses | Tags |",
        "| --- | --- | --- | --- | --- |",
    ]

    endpoint_count = 0
    for path in sorted(paths):
        path_item = paths[path]
        if not isinstance(path_item, Mapping):
            continue
        for method in _HTTP_METHODS:
            operation = path_item.get(method)
            if not isinstance(operation, Mapping):
                continue
            tags = operation.get("tags")
            tag_text = ", ".join(str(tag) for tag in tags) if isinstance(tags, list) else "—"
            responses = operation.get("responses")
            response_text = (
                ", ".join(f"`{code}`" for code in sorted(responses))
                if isinstance(responses, Mapping)
                else "—"
            )
            lines.append(
                "| "
                f"`{method.upper()}` | `{_markdown_cell(path)}` | "
                f"{_markdown_cell(operation.get('summary'))} | {response_text} | "
                f"{_markdown_cell(tag_text)} |"
            )
            endpoint_count += 1

    if endpoint_count == 0:
        lines.append("| — | — | No documented endpoints | — | — |")

    lines.extend([
        "",
        "## Contract checks",
        "",
        "The contract suite validates operation metadata, request examples, parameter "
        "descriptions, strict schemas, and responses against this snapshot. CI also compares "
        "the snapshot with `origin/main` and rejects breaking changes.",
        "",
    ])
    return "\n".join(lines)


def _write_or_check(path: Path, expected: str, *, check: bool) -> bool:
    if check:
        try:
            actual = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            sys.stderr.write(f"out of date: {path} does not exist\n")
            return False
        if actual != expected:
            sys.stderr.write(f"out of date: regenerate {path}\n")
            return False
        sys.stdout.write(f"up to date: {path}\n")
        return True

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8", newline="\n")
    sys.stdout.write(f"generated: {path}\n")
    return True


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(argv)
    schema = _load_openapi(args.source_root)
    outputs = [(args.schema_output, _serialize_schema(schema))]
    if not args.schema_only:
        outputs.append((
            args.docs_output,
            _render_api_docs(schema, args.schema_output, args.docs_output),
        ))

    results = [_write_or_check(path, content, check=args.check) for path, content in outputs]
    return 0 if all(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
